language: node_js
node_js:
  - 10

services:
  - docker 


script:
  - docker build -t minalmahor/reactapp .
  - docker images 

deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master

